# 基础路径配置
base_paths:
  data_dir: './data'
  model_dir: './models'
  result_dir: './results'
  pth_dir: 'pth'
  plot_dir: 'plot'
  txt_dir: 'txt'
  tensorboard_dir: 'tensorboard_logs'

# 模型参数配置
model_params:
  latent_dim: 10
  intermediate_dim: [512,1024,2048]
  learning_rate: 1.0e-4
  use_lr_scheduler: True
  batch_size: 128
  epochs: 1000
  device: "cuda:0"
  encoder_type: "basic"
  pretrain_epochs: 300
  clustering_method: 'leiden'
  resolution: 0.8 #initial
  train_config:
    save_interval: 50
    update_interval: 50
    early_stop_patience: 5
    min_loss_threshold:
      total: 0.5
      recon: 0.02
    tsne_plot: True
    recon_plot: False

  basic_parameters:
    latent_dim: 10
    intermediate_dim: [512,1024,2048]
  cnn_parameters:
    cnn1: 32
    cnn2: 64
    cnn3: 128
  advanced_parameters:
    cnn1: 32
    cnn2: 64
    cnn3: 128

# 权重调度器配置
weight_scheduler:
  init_weights:
    lamb1: 100  # 重构损失
    lamb2: 1    # GMM先验的KL散度  
    lamb3: 1    # GMM熵项
    lamb4: 1  # 先验损失, M2-1, OT-10,100
    lamb5: 0    # 峰加权损失，替换Recon_Loss
    lamb6: 1000 # Match Loss of S
    lamb7: 0    # Unsimilarity between S
  max_weights:
    lamb1: 100  # 重构损失
    lamb2: 1    # GMM先验的KL散度  
    lamb3: 1    # GMM熵项
    lamb4: 1  # 先验损失, M2-1, OT-10,100
    lamb5: 0    # 峰加权损失，替换Recon_Loss
    lamb6: 1000 # Match Loss of S
    lamb7: 0    # Unsimilarity between S